### ISSUE TITLE
"Wrong size for extra data https://[...]/flash_player_sa_linuxx86_64.tar.gz"

### ISSUE THREAD

**Issue by Wowfunhappy** [flathub/com.adobe.Flash-Player-Projector#6]
When I try to install this from flathub on my machine, I got the following error:

`Failed to install com.adobe.Flash-Player-Projector/x86_64/stable: Wrong size for extra data https://fpdownload.macromedia.com/pub/flashplayer/updaters/31/flash_player_sa_linuxx86_64.tar.gz`

I'm guessing Adobe changed something? Can this be fixed?

**Comment by hadess** [comment]
> I'm guessing Adobe changed something? Can this be fixed?

They changed the binary without changing the filename. That's going to keep happening until we can automate updates somehow. This particular one is fixed now, don't hesitate to file bugs if it happens again.

**Comment by Wowfunhappy** [comment]
Thanks! I'm still getting the error, I assume it takes some time for Flathub to update?

**Comment by hadess** [comment]
Yes, it takes a while. You'll know it'll work when version "31.0.0.122" is mentioned on https://flathub.org/apps/details/com.adobe.Flash-Player-Projector

**Comment by duvjones** [comment]
I guess that I can assume that this happened again for version 31.0.0.148?

**Comment by hadess** [comment]
> I guess that I can assume that this happened again for version 31.0.0.148?

Which was fixed in #7 (commit 178f50164452007d756436f66dc59aa52d0b59b8). I'll let you dig out the references yourself next time, there's less than a dozen commits, issues, and merge requests :)

**Comment by duvjones** [comment]
Hmmm, then it might be something on my end... because I am still getting that error, any ideas that might help??
